project:
  type: website

website:
  title: "Yahya's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/yahyarahhawi
      - icon: linkedin
        href: https://www.linkedin.com/in/yahyarahhawi
  search: true

format:
  html:
    theme: cosmo
    toc: true