project:
  type: website
  output-dir: docs

website:
  title: "Yahya's Blog"
  site-url: "https://yahyarahhawi.github.io"
  navbar:
    right:
      - text: "Posts"
        file: posts/index.qmd
      - about.qmd
      - icon: github
        href: https://github.com/yahyarahhawi
      - icon: linkedin
        href: https://www.linkedin.com/in/yahyarahhawi
  search: true

format:
  html:
    theme: cosmo
    toc: true
    code-fold: false